const a = 3, b =2;
console.log(a>b)
console.log(5 == 5);
console.log(2 == "2");
console.log("hello" == "Hello");
console.log(2 != 2);
console.log(2 != "2");
console.log(2!= 3);
console.log(2 === 2);
console.log(2 === "2");
console.log(2 !== 2);
console.log(2 !== "2");
console.log("Hello" !== "World");
console.log(3 > 2);
console.log(4 > 4);
console.log(2 > 5);
console.log(3 >= 2);
console.log(4 >= 4);
console.log(2 >= 5);
console.log(2 < 5);
console.log(4 < 4);
console.log(3 < 2);
console.log(2 <= 5);
console.log(4 <= 4);
console.log(3 <= 2);
const x = 5, y = 3;
console.log((x < 6) && (y < 5));
let x1 = 2;
console.log((x1 < 4) && (4 >= x1));
console.log((x1 <= 4) && (2 == 4));
console.log((x1 > 4) && (x1 == 4));
console.log((x1 < 4) || (4 >=x1));
console.log((x1 <= 4) || (2 == 4));
console.log((x1 > 4) || (x1 == 4));
console.log(!true);
console.log(!false);
console.log(!(2 < 3));